### PR TITLE
Initial example added for ble-scan

### PR DESCRIPTION
**Pull request by Bucknalla**
Preparing PR - Checking if any additional content is required.

### CODE REVIEW

**Comment by ntzovanis** [comment]
@Bucknalla what are we missing to merge this PR?

**Comment by Bucknalla** [comment]
@ntzovanis I'm not sure the linter doesn't seem very happy... I've got the correctly formatted commits, so I'm not sure why it's complaining...

**Comment by Bucknalla** [comment]
I've done a rebase and cleaned up the commits so hopefully it'll pass now @ntzovanis

**Comment by ntzovanis** [comment]
Maybe @nazrhom can give us a hand with the CI.

**Pull request closed without merging**
